# Generated by Django 5.1.3 on 2025-01-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campista',
            fields=[
                ('idCam', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCampista', models.TextField(max_length=250)),
                ('correoCampista', models.EmailField(max_length=254)),
                ('telefonoCampista', models.TextField(max_length=10)),
                ('direccionCampista', models.TextField(max_length=250)),
            ],
        ),
    ]
