# Generated by Django 5.1.3 on 2025-01-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campista',
            name='direccionCampista',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campista',
            name='nombreCampista',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='campista',
            name='telefonoCampista',
            field=models.CharField(max_length=10),
        ),
    ]
