# Generated by Django 5.1.3 on 2025-01-09 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camping', '0002_alter_campista_direccioncampista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idRes', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('fechaFinal', models.DateField()),
                ('tipoAlojamiento', models.CharField(max_length=250)),
                ('numeroPersona', models.CharField(max_length=250)),
                ('estadoReserva', models.CharField(max_length=250)),
                ('observacionReserva', models.TextField(max_length=250)),
                ('campista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='Camping.campista')),
            ],
        ),
    ]
